### PR TITLE
Fix Cyprus translation in Turkish

### PR DESCRIPTION
**Pull request by victor-paumier**

### CODE REVIEW

**Comment by victor-paumier** [comment]
Changed 'Güney Kıbrıs Rum Kesimi' by 'Kıbrıs' because the old one is about Greek part of Cyprus

**Comment by fabpot** [comment]
This is a read-only repository. The master version is at symfony/symfony. Anyway, we won't accept this change as this file is generated from the ICU data, where the change should be made. Sorry, closing this now.

**Comment by victor-paumier** [comment]
Oh ok sorry, I didn't get it. 
I checked on ICU data and it appears that this issue has been fixed on their last release (v. 57) but the symfony/symfony master version is currently using the v. 55. So, do you have an idea of the frequency update of the ICU data on the symfony/symfony repository? Thank you!

**Comment by fabpot** [comment]
Can you open a ticket on that topic on symfony/symfony?

**Comment by victor-paumier** [comment]
Ok no problem, I'll do it now. Thanks

**Pull request closed without merging**
